/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : string,
  'date' : string,
  'note' : string,
  'tripId' : string,
  'category' : string,
  'amount' : number,
}
export interface TripPlan {
  'id' : string,
  'destination' : string,
  'accommodationCost' : number,
  'createdAt' : bigint,
  'numberOfDays' : bigint,
  'preferences' : Array<string>,
  'numberOfTravelers' : bigint,
  'miscCost' : number,
  'totalBudget' : number,
  'sightseeingCost' : number,
  'transportCost' : number,
  'itinerary' : Array<string>,
  'foodCost' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[string, string, string, number, string], Expense>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTripPlan' : ActorMethod<
    [string, bigint, bigint, number, Array<string>],
    TripPlan
  >,
  'deleteExpense' : ActorMethod<[string], boolean>,
  'deleteTripPlan' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[string], Array<Expense>>,
  'getTripPlan' : ActorMethod<[string], TripPlan>,
  'getTripPlans' : ActorMethod<[], Array<TripPlan>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];