/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'tripId' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TripPlan = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'accommodationCost' : IDL.Float64,
  'createdAt' : IDL.Int,
  'numberOfDays' : IDL.Nat,
  'preferences' : IDL.Vec(IDL.Text),
  'numberOfTravelers' : IDL.Nat,
  'miscCost' : IDL.Float64,
  'totalBudget' : IDL.Float64,
  'sightseeingCost' : IDL.Float64,
  'transportCost' : IDL.Float64,
  'itinerary' : IDL.Vec(IDL.Text),
  'foodCost' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [Expense],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTripPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Vec(IDL.Text)],
      [TripPlan],
      [],
    ),
  'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTripPlan' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getTripPlan' : IDL.Func([IDL.Text], [TripPlan], ['query']),
  'getTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'tripId' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TripPlan = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'accommodationCost' : IDL.Float64,
    'createdAt' : IDL.Int,
    'numberOfDays' : IDL.Nat,
    'preferences' : IDL.Vec(IDL.Text),
    'numberOfTravelers' : IDL.Nat,
    'miscCost' : IDL.Float64,
    'totalBudget' : IDL.Float64,
    'sightseeingCost' : IDL.Float64,
    'transportCost' : IDL.Float64,
    'itinerary' : IDL.Vec(IDL.Text),
    'foodCost' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [Expense],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTripPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64, IDL.Vec(IDL.Text)],
        [TripPlan],
        [],
      ),
    'deleteExpense' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTripPlan' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getTripPlan' : IDL.Func([IDL.Text], [TripPlan], ['query']),
    'getTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };